-- CreateTable
CREATE TABLE `task` (
    `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `titleTask` VARCHAR(255) NOT NULL,
    `descriptionTask` VARCHAR(255) NOT NULL,
    `isCompleted` BOOLEAN NOT NULL DEFAULT false,
    `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
